In [1]:
import pandas as pd
df = pd.read_csv('./data/delivery_time.csv')
df

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176
...,...,...,...,...,...,...,...
995,2022-10-10 03:13:30,2022-10-10 04:13:48,2022-10-10 04:15:37,배고팡,1.79,현금,user_186
996,2023-02-03 12:47:19,2023-02-03 13:11:46,2023-02-03 13:12:57,배고팡,15.55,카드,user_239
997,2023-01-05 21:28:58,2023-01-05 21:57:41,2023-01-05 21:57:44,배고팡,8.33,현금,user_264
998,2023-06-15 03:56:42,2023-06-15 04:14:24,2023-06-15 04:18:38,여기여,8.20,앱결제,user_229
999,2023-08-02 20:53:53,2023-08-02 22:04:06,2023-08-02 22:09:22,여기여,5.33,카드,user_148

### 풀이

In [2]:
# datetime 자료형으로 변경
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
print(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
print(df['예상도착시간'])

0     2023-07-26 09:14:06
1     2022-11-07 10:44:04
2     2023-04-18 06:12:46
3     2023-08-18 11:16:25
4     2023-08-11 11:27:57
              ...
995   2022-10-10 04:13:48
996   2023-02-03 13:11:46
997   2023-01-05 21:57:41
998   2023-06-15 04:14:24
999   2023-08-02 22:04:06
Name: 실제도착시간, Length: 1000, dtype: datetime64[ns]
0     2023-07-26 08:39:42
1     2022-11-07 10:50:15
2     2023-04-18 05:32:53
3     2023-08-18 11:08:33
4     2023-08-11 10:51:57
              ...
995   2022-10-10 04:15:37
996   2023-02-03 13:12:57
997   2023-01-05 21:57:44
998   2023-06-15 04:18:38
999   2023-08-02 22:09:22
Name: 예상도착시간, Length: 1000, dtype: datetime64[ns]

In [3]:
# 지연 시간 계산(분)
df['지연시간'] = (df['실제도착시간'] - df['예상도착시간']).dt.total_seconds()/60    # 분 단위로 게산
df

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,지연시간
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275,34.400000
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360,-6.183333
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36,39.883333
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65,7.866667
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176,36.000000
...,...,...,...,...,...,...,...,...
995,2022-10-10 03:13:30,2022-10-10 04:13:48,2022-10-10 04:15:37,배고팡,1.79,현금,user_186,-1.816667
996,2023-02-03 12:47:19,2023-02-03 13:11:46,2023-02-03 13:12:57,배고팡,15.55,카드,user_239,-1.183333
997,2023-01-05 21:28:58,2023-01-05 21:57:41,2023-01-05 21:57:44,배고팡,8.33,현금,user_264,-0.050000
998,2023-06-15 03:56:42,2023-06-15 04:14:24,2023-06-15 04:18:38,여기여,8.20,앱결제,user_229,-4.233333
999,2023-08-02 20:53:53,2023-08-02 22:04:06,2023-08-02 22:09:22,여기여,5.33,카드,user_148,-5.266667

In [5]:
# 실제 도착 시간이 예상 도착 시간보다 늦은 경우를 체크하는 컬럼 생성
df['지연여부'] = df['지연시간'] > 0
df

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user,지연시간,지연여부
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275,34.400000,True
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360,-6.183333,False
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36,39.883333,True
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65,7.866667,True
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176,36.000000,True
...,...,...,...,...,...,...,...,...,...
995,2022-10-10 03:13:30,2022-10-10 04:13:48,2022-10-10 04:15:37,배고팡,1.79,현금,user_186,-1.816667,False
996,2023-02-03 12:47:19,2023-02-03 13:11:46,2023-02-03 13:12:57,배고팡,15.55,카드,user_239,-1.183333,False
997,2023-01-05 21:28:58,2023-01-05 21:57:41,2023-01-05 21:57:44,배고팡,8.33,현금,user_264,-0.050000,False
998,2023-06-15 03:56:42,2023-06-15 04:14:24,2023-06-15 04:18:38,여기여,8.20,앱결제,user_229,-4.233333,False
999,2023-08-02 20:53:53,2023-08-02 22:04:06,2023-08-02 22:09:22,여기여,5.33,카드,user_148,-5.266667,False

In [6]:
# 결제 종류별 지연된 주문 수의 비율 계산
result = df.groupby('결제종류')['지연여부'].mean()
result

결제종류
앱결제    0.556634
카드     0.489971
현금     0.488304
Name: 지연여부, dtype: float64

In [7]:
# 가장 비율이 높은 값
print(round(result.max(), 2))

0.56